---
- name: create user
  user: name={{item}} state=present
  with_items: "{{createUser}}"

- name: yum nginx master
  yum: name=nginx state=present

# 如果目标主机上的 nginx.conf 文件发生改变,就会运行 handlers 中的 reload nginx server 任务
- name: update nginx main config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  tags: tag_update_config
  notify: reload nginx server

# 如果目标主机上的 www.example.com.conf 文件发生改变,就会运行 handlers 中的 reload nginx server 任务
- name: add virtualhost config
  copy: 
    src: www.example.com.conf 
    dest: /etc/nginx/conf.d/
  tags: tag_update_config
  notify: reload nginx server

- name: check nginx syntax
  shell: /usr/sbin/nginx -t
  register: nginx_syntax_result
  tags: tag_update_config

- name: check nginx running
  stat: path=/var/run/nginx.pid
  register: nginx_running_result
  tags: tag_update_config

- name: print nginx syntax
  debug: var=nginx_syntax_result

- name: print nginx running
  debug: var=nginx_running_result

- name: start nginx server
  systemd: name=nginx state=started
  when:
    - nginx_syntax_result.rc == 0  
    - nginx_running_result.stat.exists == false
