---
- name: tags playbook example
  hosts: master
  gather_facts: no
  vars:
    createUser:
      - tomcat
      - www
      - mysql
  tasks:
    - name: create user
      user: name={{item}} state=present
      with_items: "{{createUser}}"

    - name: yum nginx master
      yum: name=nginx state=present

    - name: update nginx main config
      copy: src=nginx.conf dest=/etc/nginx/
      tags: tag_update_config

    - name: add virtualhost config
      copy: src=www.example.com.conf dest=/etc/nginx/conf.d/
      tags: tag_update_config
    
    - name: check nginx syntax
      shell: /usr/sbin/nginx -t
      register: nginx_syntax_result
      tags: tag_update_config

    - name: check nginx running
      stat: path=/var/run/nginx.pid
      register: nginx_running_result
      tags: tag_update_config

    - name: print nginx syntax
      debug: var=nginx_syntax_result

    - name: print nginx running
      debug: var=nginx_running_result

    - name: reload nginx server
      systemd: name=nginx state=reloaded
      # when: nginx_syntax_result.rc == 0 and nginx_running_result.stat.exists == true
      # when 也可以用下面的方式表示 and 关系
      when:
        - nginx_syntax_result.rc == 0
        - nginx_running_result.stat.exists == true
      tags: tag_update_config

    - name: start nginx server
      systemd: name=nginx state=started
      when: nginx_syntax_result.rc == 0